# Generated by Django 6.0.7 on 2026-07-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=255)),
                ('teacher_dept', models.CharField(max_length=255)),
                ('teacher_designation', models.CharField(max_length=255)),
            ],
        ),
    ]
