# Generated by Django 6.0.7 on 2026-07-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_dept', models.CharField(max_length=255)),
                ('emp_designation', models.CharField(max_length=255)),
            ],
        ),
    ]
