# Generated by Django 6.0.7 on 2026-07-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
