# Generated by Django 6.0.7 on 2026-08-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.ImageField(upload_to='profiles/')),
                ('file1', models.FileField(upload_to='files/')),
            ],
        ),
    ]
