# Generated by Django 6.0.7 on 2026-08-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_APP', '0002_comment_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
